name: Python api documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -e .
          pip install pdoc3 ghp-import

      - name: Build documentation
        run: |
          source venv/bin/activate
          pdoc --html --output-dir docs/ ../cybertensor

      - name: Deploy to GitHub Pages, Run ghp-import
        run: |
          source venv/bin/activate
          ghp-import -n -p -f docs/cybertensor
